services:
  mariadb:
    image: mariadb:11
    container_name: calculator-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: calculator
      MYSQL_USER: calculatoruser
      MYSQL_PASSWORD: calculatorpass
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 5s
      retries: 20

  flyway:
    image: flyway/flyway:10
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - ./db/migrations:/flyway/sql
    command: >
      -url=jdbc:mariadb://mariadb:3306/calculator
      -user=calculatoruser
      -password=calculatorpass
      migrate